/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_rectangle.h"

static const char* CMockString_length = "length";
static const char* CMockString_new_length = "new_length";
static const char* CMockString_new_width = "new_width";
static const char* CMockString_rectangle_get_area = "rectangle_get_area";
static const char* CMockString_rectangle_get_perimeter = "rectangle_get_perimeter";
static const char* CMockString_rectangle_init = "rectangle_init";
static const char* CMockString_rectangle_is_square = "rectangle_is_square";
static const char* CMockString_rectangle_set_length = "rectangle_set_length";
static const char* CMockString_rectangle_set_width = "rectangle_set_width";
static const char* CMockString_width = "width";

typedef struct _CMOCK_rectangle_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int CallOrder;
  uint16_t Expected_length;
  uint16_t Expected_width;

} CMOCK_rectangle_init_CALL_INSTANCE;

typedef struct _CMOCK_rectangle_get_area_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t ReturnVal;
  int CallOrder;

} CMOCK_rectangle_get_area_CALL_INSTANCE;

typedef struct _CMOCK_rectangle_get_perimeter_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t ReturnVal;
  int CallOrder;

} CMOCK_rectangle_get_perimeter_CALL_INSTANCE;

typedef struct _CMOCK_rectangle_is_square_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;
  int CallOrder;

} CMOCK_rectangle_is_square_CALL_INSTANCE;

typedef struct _CMOCK_rectangle_set_width_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int CallOrder;
  uint16_t Expected_new_width;

} CMOCK_rectangle_set_width_CALL_INSTANCE;

typedef struct _CMOCK_rectangle_set_length_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int CallOrder;
  uint16_t Expected_new_length;

} CMOCK_rectangle_set_length_CALL_INSTANCE;

static struct mock_rectangleInstance
{
  char rectangle_init_IgnoreBool;
  char rectangle_init_CallbackBool;
  CMOCK_rectangle_init_CALLBACK rectangle_init_CallbackFunctionPointer;
  int rectangle_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE rectangle_init_CallInstance;
  char rectangle_get_area_IgnoreBool;
  uint16_t rectangle_get_area_FinalReturn;
  char rectangle_get_area_CallbackBool;
  CMOCK_rectangle_get_area_CALLBACK rectangle_get_area_CallbackFunctionPointer;
  int rectangle_get_area_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE rectangle_get_area_CallInstance;
  char rectangle_get_perimeter_IgnoreBool;
  uint16_t rectangle_get_perimeter_FinalReturn;
  char rectangle_get_perimeter_CallbackBool;
  CMOCK_rectangle_get_perimeter_CALLBACK rectangle_get_perimeter_CallbackFunctionPointer;
  int rectangle_get_perimeter_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE rectangle_get_perimeter_CallInstance;
  char rectangle_is_square_IgnoreBool;
  bool rectangle_is_square_FinalReturn;
  char rectangle_is_square_CallbackBool;
  CMOCK_rectangle_is_square_CALLBACK rectangle_is_square_CallbackFunctionPointer;
  int rectangle_is_square_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE rectangle_is_square_CallInstance;
  char rectangle_set_width_IgnoreBool;
  char rectangle_set_width_CallbackBool;
  CMOCK_rectangle_set_width_CALLBACK rectangle_set_width_CallbackFunctionPointer;
  int rectangle_set_width_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE rectangle_set_width_CallInstance;
  char rectangle_set_length_IgnoreBool;
  char rectangle_set_length_CallbackBool;
  CMOCK_rectangle_set_length_CALLBACK rectangle_set_length_CallbackFunctionPointer;
  int rectangle_set_length_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE rectangle_set_length_CallInstance;
} Mock;

extern jmp_buf AbortFrame;
extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_rectangle_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.rectangle_init_CallInstance;
  if (Mock.rectangle_init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_rectangle_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.rectangle_init_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.rectangle_get_area_CallInstance;
  if (Mock.rectangle_get_area_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_rectangle_get_area);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.rectangle_get_area_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.rectangle_get_perimeter_CallInstance;
  if (Mock.rectangle_get_perimeter_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_rectangle_get_perimeter);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.rectangle_get_perimeter_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.rectangle_is_square_CallInstance;
  if (Mock.rectangle_is_square_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_rectangle_is_square);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.rectangle_is_square_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.rectangle_set_width_CallInstance;
  if (Mock.rectangle_set_width_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_rectangle_set_width);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.rectangle_set_width_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.rectangle_set_length_CallInstance;
  if (Mock.rectangle_set_length_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_rectangle_set_length);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.rectangle_set_length_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_rectangle_Init(void)
{
  mock_rectangle_Destroy();
}

void mock_rectangle_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

void rectangle_init(uint16_t length, uint16_t width)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rectangle_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rectangle_init);
  cmock_call_instance = (CMOCK_rectangle_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rectangle_init_CallInstance);
  Mock.rectangle_init_CallInstance = CMock_Guts_MemNext(Mock.rectangle_init_CallInstance);
  if (Mock.rectangle_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.rectangle_init_CallbackBool &&
      Mock.rectangle_init_CallbackFunctionPointer != NULL)
  {
    Mock.rectangle_init_CallbackFunctionPointer(length, width, Mock.rectangle_init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_rectangle_init,CMockString_length);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_length, length, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_rectangle_init,CMockString_width);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_width, width, cmock_line, CMockStringMismatch);
  }
  if (Mock.rectangle_init_CallbackFunctionPointer != NULL)
  {
    Mock.rectangle_init_CallbackFunctionPointer(length, width, Mock.rectangle_init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_rectangle_init(CMOCK_rectangle_init_CALL_INSTANCE* cmock_call_instance, uint16_t length, uint16_t width);
void CMockExpectParameters_rectangle_init(CMOCK_rectangle_init_CALL_INSTANCE* cmock_call_instance, uint16_t length, uint16_t width)
{
  cmock_call_instance->Expected_length = length;
  cmock_call_instance->Expected_width = width;
}

void rectangle_init_CMockIgnore(void)
{
  Mock.rectangle_init_IgnoreBool = (char)1;
}

void rectangle_init_CMockStopIgnore(void)
{
  Mock.rectangle_init_IgnoreBool = (char)0;
}

void rectangle_init_CMockExpect(UNITY_LINE_TYPE cmock_line, uint16_t length, uint16_t width)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rectangle_init_CALL_INSTANCE));
  CMOCK_rectangle_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_rectangle_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rectangle_init_CallInstance = CMock_Guts_MemChain(Mock.rectangle_init_CallInstance, cmock_guts_index);
  Mock.rectangle_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_rectangle_init(cmock_call_instance, length, width);
}

void rectangle_init_AddCallback(CMOCK_rectangle_init_CALLBACK Callback)
{
  Mock.rectangle_init_IgnoreBool = (char)0;
  Mock.rectangle_init_CallbackBool = (char)1;
  Mock.rectangle_init_CallbackFunctionPointer = Callback;
}

void rectangle_init_Stub(CMOCK_rectangle_init_CALLBACK Callback)
{
  Mock.rectangle_init_IgnoreBool = (char)0;
  Mock.rectangle_init_CallbackBool = (char)0;
  Mock.rectangle_init_CallbackFunctionPointer = Callback;
}

uint16_t rectangle_get_area(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rectangle_get_area_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rectangle_get_area);
  cmock_call_instance = (CMOCK_rectangle_get_area_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rectangle_get_area_CallInstance);
  Mock.rectangle_get_area_CallInstance = CMock_Guts_MemNext(Mock.rectangle_get_area_CallInstance);
  if (Mock.rectangle_get_area_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.rectangle_get_area_FinalReturn;
    Mock.rectangle_get_area_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.rectangle_get_area_CallbackBool &&
      Mock.rectangle_get_area_CallbackFunctionPointer != NULL)
  {
    uint16_t cmock_cb_ret = Mock.rectangle_get_area_CallbackFunctionPointer(Mock.rectangle_get_area_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.rectangle_get_area_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.rectangle_get_area_CallbackFunctionPointer(Mock.rectangle_get_area_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void rectangle_get_area_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rectangle_get_area_CALL_INSTANCE));
  CMOCK_rectangle_get_area_CALL_INSTANCE* cmock_call_instance = (CMOCK_rectangle_get_area_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rectangle_get_area_CallInstance = CMock_Guts_MemChain(Mock.rectangle_get_area_CallInstance, cmock_guts_index);
  Mock.rectangle_get_area_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.rectangle_get_area_IgnoreBool = (char)1;
}

void rectangle_get_area_CMockStopIgnore(void)
{
  if(Mock.rectangle_get_area_IgnoreBool)
    Mock.rectangle_get_area_CallInstance = CMock_Guts_MemNext(Mock.rectangle_get_area_CallInstance);
  Mock.rectangle_get_area_IgnoreBool = (char)0;
}

void rectangle_get_area_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rectangle_get_area_CALL_INSTANCE));
  CMOCK_rectangle_get_area_CALL_INSTANCE* cmock_call_instance = (CMOCK_rectangle_get_area_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rectangle_get_area_CallInstance = CMock_Guts_MemChain(Mock.rectangle_get_area_CallInstance, cmock_guts_index);
  Mock.rectangle_get_area_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void rectangle_get_area_AddCallback(CMOCK_rectangle_get_area_CALLBACK Callback)
{
  Mock.rectangle_get_area_IgnoreBool = (char)0;
  Mock.rectangle_get_area_CallbackBool = (char)1;
  Mock.rectangle_get_area_CallbackFunctionPointer = Callback;
}

void rectangle_get_area_Stub(CMOCK_rectangle_get_area_CALLBACK Callback)
{
  Mock.rectangle_get_area_IgnoreBool = (char)0;
  Mock.rectangle_get_area_CallbackBool = (char)0;
  Mock.rectangle_get_area_CallbackFunctionPointer = Callback;
}

uint16_t rectangle_get_perimeter(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rectangle_get_perimeter_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rectangle_get_perimeter);
  cmock_call_instance = (CMOCK_rectangle_get_perimeter_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rectangle_get_perimeter_CallInstance);
  Mock.rectangle_get_perimeter_CallInstance = CMock_Guts_MemNext(Mock.rectangle_get_perimeter_CallInstance);
  if (Mock.rectangle_get_perimeter_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.rectangle_get_perimeter_FinalReturn;
    Mock.rectangle_get_perimeter_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.rectangle_get_perimeter_CallbackBool &&
      Mock.rectangle_get_perimeter_CallbackFunctionPointer != NULL)
  {
    uint16_t cmock_cb_ret = Mock.rectangle_get_perimeter_CallbackFunctionPointer(Mock.rectangle_get_perimeter_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.rectangle_get_perimeter_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.rectangle_get_perimeter_CallbackFunctionPointer(Mock.rectangle_get_perimeter_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void rectangle_get_perimeter_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rectangle_get_perimeter_CALL_INSTANCE));
  CMOCK_rectangle_get_perimeter_CALL_INSTANCE* cmock_call_instance = (CMOCK_rectangle_get_perimeter_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rectangle_get_perimeter_CallInstance = CMock_Guts_MemChain(Mock.rectangle_get_perimeter_CallInstance, cmock_guts_index);
  Mock.rectangle_get_perimeter_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.rectangle_get_perimeter_IgnoreBool = (char)1;
}

void rectangle_get_perimeter_CMockStopIgnore(void)
{
  if(Mock.rectangle_get_perimeter_IgnoreBool)
    Mock.rectangle_get_perimeter_CallInstance = CMock_Guts_MemNext(Mock.rectangle_get_perimeter_CallInstance);
  Mock.rectangle_get_perimeter_IgnoreBool = (char)0;
}

void rectangle_get_perimeter_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rectangle_get_perimeter_CALL_INSTANCE));
  CMOCK_rectangle_get_perimeter_CALL_INSTANCE* cmock_call_instance = (CMOCK_rectangle_get_perimeter_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rectangle_get_perimeter_CallInstance = CMock_Guts_MemChain(Mock.rectangle_get_perimeter_CallInstance, cmock_guts_index);
  Mock.rectangle_get_perimeter_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void rectangle_get_perimeter_AddCallback(CMOCK_rectangle_get_perimeter_CALLBACK Callback)
{
  Mock.rectangle_get_perimeter_IgnoreBool = (char)0;
  Mock.rectangle_get_perimeter_CallbackBool = (char)1;
  Mock.rectangle_get_perimeter_CallbackFunctionPointer = Callback;
}

void rectangle_get_perimeter_Stub(CMOCK_rectangle_get_perimeter_CALLBACK Callback)
{
  Mock.rectangle_get_perimeter_IgnoreBool = (char)0;
  Mock.rectangle_get_perimeter_CallbackBool = (char)0;
  Mock.rectangle_get_perimeter_CallbackFunctionPointer = Callback;
}

bool rectangle_is_square(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rectangle_is_square_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rectangle_is_square);
  cmock_call_instance = (CMOCK_rectangle_is_square_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rectangle_is_square_CallInstance);
  Mock.rectangle_is_square_CallInstance = CMock_Guts_MemNext(Mock.rectangle_is_square_CallInstance);
  if (Mock.rectangle_is_square_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.rectangle_is_square_FinalReturn;
    Mock.rectangle_is_square_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.rectangle_is_square_CallbackBool &&
      Mock.rectangle_is_square_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.rectangle_is_square_CallbackFunctionPointer(Mock.rectangle_is_square_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.rectangle_is_square_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.rectangle_is_square_CallbackFunctionPointer(Mock.rectangle_is_square_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void rectangle_is_square_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rectangle_is_square_CALL_INSTANCE));
  CMOCK_rectangle_is_square_CALL_INSTANCE* cmock_call_instance = (CMOCK_rectangle_is_square_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rectangle_is_square_CallInstance = CMock_Guts_MemChain(Mock.rectangle_is_square_CallInstance, cmock_guts_index);
  Mock.rectangle_is_square_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.rectangle_is_square_IgnoreBool = (char)1;
}

void rectangle_is_square_CMockStopIgnore(void)
{
  if(Mock.rectangle_is_square_IgnoreBool)
    Mock.rectangle_is_square_CallInstance = CMock_Guts_MemNext(Mock.rectangle_is_square_CallInstance);
  Mock.rectangle_is_square_IgnoreBool = (char)0;
}

void rectangle_is_square_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rectangle_is_square_CALL_INSTANCE));
  CMOCK_rectangle_is_square_CALL_INSTANCE* cmock_call_instance = (CMOCK_rectangle_is_square_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rectangle_is_square_CallInstance = CMock_Guts_MemChain(Mock.rectangle_is_square_CallInstance, cmock_guts_index);
  Mock.rectangle_is_square_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void rectangle_is_square_AddCallback(CMOCK_rectangle_is_square_CALLBACK Callback)
{
  Mock.rectangle_is_square_IgnoreBool = (char)0;
  Mock.rectangle_is_square_CallbackBool = (char)1;
  Mock.rectangle_is_square_CallbackFunctionPointer = Callback;
}

void rectangle_is_square_Stub(CMOCK_rectangle_is_square_CALLBACK Callback)
{
  Mock.rectangle_is_square_IgnoreBool = (char)0;
  Mock.rectangle_is_square_CallbackBool = (char)0;
  Mock.rectangle_is_square_CallbackFunctionPointer = Callback;
}

void rectangle_set_width(uint16_t new_width)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rectangle_set_width_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rectangle_set_width);
  cmock_call_instance = (CMOCK_rectangle_set_width_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rectangle_set_width_CallInstance);
  Mock.rectangle_set_width_CallInstance = CMock_Guts_MemNext(Mock.rectangle_set_width_CallInstance);
  if (Mock.rectangle_set_width_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.rectangle_set_width_CallbackBool &&
      Mock.rectangle_set_width_CallbackFunctionPointer != NULL)
  {
    Mock.rectangle_set_width_CallbackFunctionPointer(new_width, Mock.rectangle_set_width_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_rectangle_set_width,CMockString_new_width);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_new_width, new_width, cmock_line, CMockStringMismatch);
  }
  if (Mock.rectangle_set_width_CallbackFunctionPointer != NULL)
  {
    Mock.rectangle_set_width_CallbackFunctionPointer(new_width, Mock.rectangle_set_width_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_rectangle_set_width(CMOCK_rectangle_set_width_CALL_INSTANCE* cmock_call_instance, uint16_t new_width);
void CMockExpectParameters_rectangle_set_width(CMOCK_rectangle_set_width_CALL_INSTANCE* cmock_call_instance, uint16_t new_width)
{
  cmock_call_instance->Expected_new_width = new_width;
}

void rectangle_set_width_CMockIgnore(void)
{
  Mock.rectangle_set_width_IgnoreBool = (char)1;
}

void rectangle_set_width_CMockStopIgnore(void)
{
  Mock.rectangle_set_width_IgnoreBool = (char)0;
}

void rectangle_set_width_CMockExpect(UNITY_LINE_TYPE cmock_line, uint16_t new_width)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rectangle_set_width_CALL_INSTANCE));
  CMOCK_rectangle_set_width_CALL_INSTANCE* cmock_call_instance = (CMOCK_rectangle_set_width_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rectangle_set_width_CallInstance = CMock_Guts_MemChain(Mock.rectangle_set_width_CallInstance, cmock_guts_index);
  Mock.rectangle_set_width_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_rectangle_set_width(cmock_call_instance, new_width);
}

void rectangle_set_width_AddCallback(CMOCK_rectangle_set_width_CALLBACK Callback)
{
  Mock.rectangle_set_width_IgnoreBool = (char)0;
  Mock.rectangle_set_width_CallbackBool = (char)1;
  Mock.rectangle_set_width_CallbackFunctionPointer = Callback;
}

void rectangle_set_width_Stub(CMOCK_rectangle_set_width_CALLBACK Callback)
{
  Mock.rectangle_set_width_IgnoreBool = (char)0;
  Mock.rectangle_set_width_CallbackBool = (char)0;
  Mock.rectangle_set_width_CallbackFunctionPointer = Callback;
}

void rectangle_set_length(uint16_t new_length)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rectangle_set_length_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rectangle_set_length);
  cmock_call_instance = (CMOCK_rectangle_set_length_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rectangle_set_length_CallInstance);
  Mock.rectangle_set_length_CallInstance = CMock_Guts_MemNext(Mock.rectangle_set_length_CallInstance);
  if (Mock.rectangle_set_length_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.rectangle_set_length_CallbackBool &&
      Mock.rectangle_set_length_CallbackFunctionPointer != NULL)
  {
    Mock.rectangle_set_length_CallbackFunctionPointer(new_length, Mock.rectangle_set_length_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_rectangle_set_length,CMockString_new_length);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_new_length, new_length, cmock_line, CMockStringMismatch);
  }
  if (Mock.rectangle_set_length_CallbackFunctionPointer != NULL)
  {
    Mock.rectangle_set_length_CallbackFunctionPointer(new_length, Mock.rectangle_set_length_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_rectangle_set_length(CMOCK_rectangle_set_length_CALL_INSTANCE* cmock_call_instance, uint16_t new_length);
void CMockExpectParameters_rectangle_set_length(CMOCK_rectangle_set_length_CALL_INSTANCE* cmock_call_instance, uint16_t new_length)
{
  cmock_call_instance->Expected_new_length = new_length;
}

void rectangle_set_length_CMockIgnore(void)
{
  Mock.rectangle_set_length_IgnoreBool = (char)1;
}

void rectangle_set_length_CMockStopIgnore(void)
{
  Mock.rectangle_set_length_IgnoreBool = (char)0;
}

void rectangle_set_length_CMockExpect(UNITY_LINE_TYPE cmock_line, uint16_t new_length)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rectangle_set_length_CALL_INSTANCE));
  CMOCK_rectangle_set_length_CALL_INSTANCE* cmock_call_instance = (CMOCK_rectangle_set_length_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rectangle_set_length_CallInstance = CMock_Guts_MemChain(Mock.rectangle_set_length_CallInstance, cmock_guts_index);
  Mock.rectangle_set_length_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_rectangle_set_length(cmock_call_instance, new_length);
}

void rectangle_set_length_AddCallback(CMOCK_rectangle_set_length_CALLBACK Callback)
{
  Mock.rectangle_set_length_IgnoreBool = (char)0;
  Mock.rectangle_set_length_CallbackBool = (char)1;
  Mock.rectangle_set_length_CallbackFunctionPointer = Callback;
}

void rectangle_set_length_Stub(CMOCK_rectangle_set_length_CALLBACK Callback)
{
  Mock.rectangle_set_length_IgnoreBool = (char)0;
  Mock.rectangle_set_length_CallbackBool = (char)0;
  Mock.rectangle_set_length_CallbackFunctionPointer = Callback;
}

